# Generated by Django 5.2.6 on 2025-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('memory_text', models.TextField(blank=True, null=True)),
                ('card_type', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('child', 'Child')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('qr_code_data', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('nfc_data', models.TextField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('gps_location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
